### ISSUE TITLE
Qual é a fonte utilizada?

### ISSUE THREAD

**Issue by LorhanSohaky** [danlessa/Sao-Paulo-Theft-Dataset#1]
Achei interessante. Poderia dizer de onde retirou essas informações?

**Comment by danlessa** [comment]
@LorhanSohaky bom dia, a fonte é uma LAI direcionada a SSP/SP

**Comment by LorhanSohaky** [comment]
@danlessa , você tem o link? Não achei nada semelhando ao que você encontrou
